<a href="https://colab.research.google.com/github/Vishu-Gupta/MLProjects/blob/main/Bacteria_Species_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This file is for a Kaggle competition of Tabular Playground Feb'22.

Bacteria species are to be predicted

In [ ]:
## code for connecting to Kaggle Datasets
!pip install kaggle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!mkdir ~/.kaggle

In [ ]:
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/kaggle.json
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle competitions download tabular-playground-series-feb-2022

 91% 163M/178M [00:01<00:00, 157MB/s]
100% 178M/178M [00:01<00:00, 156MB/s]
  0% 0.00/255k [00:00<?, ?B/s]
100% 255k/255k [00:00<00:00, 71.7MB/s]
 83% 73.0M/88.1M [00:00<00:00, 173MB/s]
100% 88.1M/88.1M [00:00<00:00, 195MB/s]


In [ ]:
!unzip test.csv.zip
!unzip train.csv.zip

Archive:  test.csv.zip
  inflating: test.csv                
Archive:  train.csv.zip
  inflating: train.csv               


In [ ]:
!rm test.csv.zip
!rm train.csv.zip

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('train.csv')

In [ ]:
data.shape

(200000, 288)

In [ ]:
list(data.columns)[-1]

'target'

In [ ]:
list(data.columns)[-2]

'A10T0G0C0'

In [ ]:
data = data.set_index('row_id')

In [ ]:
X = data.drop('target',axis=1)
y = data.pop('target')

In [ ]:
X.shape

(200000, 286)

In [ ]:
y.shape

(200000,)

In [ ]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
y_encoded = encode.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_validate,y_train,y_validate = train_test_split(X,y_encoded,train_size=0.8,stratify=y)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
model = dt.fit(X_train,y_train)

In [ ]:
y_train_pred = model.predict(X_train)
y_validate_pred = model.predict(X_validate)

In [ ]:
from sklearn.metrics import precision_score,accuracy_score,recall_score

In [ ]:
precision_score(y_train,y_train_pred,average=None)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
precision_score(y_validate,y_validate_pred,average=None)

array([0.98209846, 0.98795181, 0.97243799, 0.96464393, 0.96562108,
       0.98522784, 0.98050975, 0.98026973, 0.97661692, 0.97206983])

In [ ]:
recall_score(y_train,y_train_pred,average=None)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
recall_score(y_validate,y_validate_pred,average=None)

array([0.98063555, 0.98081236, 0.97292555, 0.96367735, 0.96513669,
       0.99143361, 0.9795307 , 0.98469644, 0.97783313, 0.97085928])

In [ ]:
y.value_counts()

Bacteroides_fragilis        20139
Streptococcus_pyogenes      20076
Streptococcus_pneumoniae    20074
Campylobacter_jejuni        20063
Salmonella_enterica         20030
Escherichia_coli            19958
Enterococcus_hirae          19947
Escherichia_fergusonii      19937
Staphylococcus_aureus       19929
Klebsiella_pneumoniae       19847
Name: target, dtype: int64

In [ ]:
test_data = pd.read_csv('test.csv')

In [ ]:
test_data.shape

(100000, 287)

In [ ]:
X_test = test_data.set_index('row_id')

In [ ]:
X_test.shape

(100000, 286)

In [ ]:
y_test_pred = model.predict(X_test)

In [ ]:
y_test = encode.inverse_transform(y_test_pred)

In [ ]:
test_data['target'] = y_test

In [ ]:
submission = test_data[['row_id','target']]

In [ ]:
submission.to_csv('submission.csv',index=False)

In [ ]:
#!kaggle competitions submit -c tabular-playground-series-feb-2022 -f submission.csv -m 'Using Decision tree'

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier()
model_rf = rf.fit(X_train,y_train)


In [ ]:
y_rf_train = model_rf.predict(X_train)
y_rf_validate = model_rf.predict(X_validate)

In [ ]:
precision_score(y_train,y_rf_train,average=None)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
precision_score(y_validate,y_rf_validate,average=None)

array([0.99479167, 0.99526657, 0.99421238, 0.99225194, 0.99596977,
       0.99348208, 0.99549324, 0.99274637, 0.99526066, 0.99129137])

In [ ]:
recall_score(y_train,y_rf_train,average=None)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
recall_score(y_validate,y_rf_validate,average=None)

array([0.99577954, 0.99551458, 0.9904738 , 0.99448898, 0.9917231 ,
       0.99848828, 0.99251123, 0.99573507, 0.99377335, 0.99227895])

In [ ]:
y_rf_test = model_rf.predict(X_test)

In [ ]:
test_data['predict_rf'] = encode.inverse_transform(y_rf_test)

In [ ]:
test_data[['row_id','predict_rf']].rename(columns={"predict_rf":"target"}).to_csv('submission_rf.csv',index=False)

In [ ]:
#!kaggle competitions submit -c tabular-playground-series-feb-2022 -f submission_rf.csv -m 'Using Random Forest'

In [ ]:
keys= np.array(list(set(y_rf_test))).reshape(-1,)

In [ ]:
score = pd.DataFrame(keys,columns=['Label_Id'])

In [ ]:
score['Label'] = encode.inverse_transform(score['Label_Id'])

In [ ]:
score['dt_train_precision'] = precision_score(y_train,y_train_pred,average=None).reshape(-1,)
score['dt_validate_precision'] = precision_score(y_validate,y_validate_pred,average=None).reshape(-1,)
score['dt_train_recall'] = recall_score(y_train,y_train_pred,average=None).reshape(-1,)
score['dt_validate_recall'] = recall_score(y_validate,y_validate_pred,average=None).reshape(-1,)

In [ ]:
score

Label_Id                     Label  ...  dt_train_recall  dt_validate_recall
0         0      Bacteroides_fragilis  ...              1.0            0.980636
1         1      Campylobacter_jejuni  ...              1.0            0.980812
2         2        Enterococcus_hirae  ...              1.0            0.972926
3         3          Escherichia_coli  ...              1.0            0.963677
4         4    Escherichia_fergusonii  ...              1.0            0.965137
5         5     Klebsiella_pneumoniae  ...              1.0            0.991434
6         6       Salmonella_enterica  ...              1.0            0.979531
7         7     Staphylococcus_aureus  ...              1.0            0.984696
8         8  Streptococcus_pneumoniae  ...              1.0            0.977833
9         9    Streptococcus_pyogenes  ...              1.0            0.970859

[10 rows x 6 columns]

In [ ]:
score['rf_train_precision'] = precision_score(y_train,y_rf_train,average=None).reshape(-1,)
score['rf_validate_precision'] = precision_score(y_validate,y_rf_validate,average=None).reshape(-1,)
score['rf_train_recall'] = recall_score(y_train,y_rf_train,average=None).reshape(-1,)
score['rf_validate_recall'] = recall_score(y_validate,y_rf_validate,average=None).reshape(-1,)

In [ ]:
score

Label_Id                     Label  ...  rf_train_recall  rf_validate_recall
0         0      Bacteroides_fragilis  ...              1.0            0.995780
1         1      Campylobacter_jejuni  ...              1.0            0.995515
2         2        Enterococcus_hirae  ...              1.0            0.990474
3         3          Escherichia_coli  ...              1.0            0.994489
4         4    Escherichia_fergusonii  ...              1.0            0.991723
5         5     Klebsiella_pneumoniae  ...              1.0            0.998488
6         6       Salmonella_enterica  ...              1.0            0.992511
7         7     Staphylococcus_aureus  ...              1.0            0.995735
8         8  Streptococcus_pneumoniae  ...              1.0            0.993773
9         9    Streptococcus_pyogenes  ...              1.0            0.992279

[10 rows x 10 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
model_knn = knn.fit(X_train,y_train)

In [ ]:
y_knn_train= model_knn.predict(X_train)
y_knn_validate = model_knn.predict(X_validate)

In [ ]:
score['knn_train_precision'] =precision_score(y_train,y_knn_train,average=None).reshape(-1,)
score['knn_validate_precision'] =precision_score(y_validate,y_knn_validate,average=None).reshape(-1,)
score['knn_train_recall'] =recall_score(y_train,y_knn_train,average=None).reshape(-1,)
score['knn_train_recall'] =recall_score(y_validate,y_knn_validate,average=None).reshape(-1,)


In [ ]:
score

Label_Id                     Label  ...  knn_validate_precision  knn_train_recall
0         0      Bacteroides_fragilis  ...                0.968907          0.959285
1         1      Campylobacter_jejuni  ...                0.963524          0.967605
2         2        Enterococcus_hirae  ...                0.941453          0.955377
3         3          Escherichia_coli  ...                0.951238          0.962675
4         4    Escherichia_fergusonii  ...                0.954670          0.961374
5         5     Klebsiella_pneumoniae  ...                0.976732          0.973041
6         6       Salmonella_enterica  ...                0.966599          0.953570
7         7     Staphylococcus_aureus  ...                0.954897          0.961365
8         8  Streptococcus_pneumoniae  ...                0.963989          0.953425
9         9    Streptococcus_pyogenes  ...                0.952870          0.946700

[10 rows x 13 columns]

In [ ]:
pred_train = pd.DataFrame(y_train_pred,columns=['DT_pred'])
pred_train['RF_pred'] = y_rf_train
pred_train['KNN_pred'] = y_knn_train

In [ ]:
from scipy import stats

In [ ]:
pred_train['ensemble_pred'] = pred_train.apply(lambda x:list(x),axis=1)

In [ ]:
pred_train['ensemble_pred'].head(100)

0     [4, 4, 4]
1     [2, 2, 2]
2     [9, 9, 9]
3     [6, 6, 6]
4     [8, 8, 8]
        ...    
95    [0, 0, 0]
96    [3, 3, 3]
97    [9, 9, 9]
98    [5, 5, 5]
99    [4, 4, 4]
Name: ensemble_pred, Length: 100, dtype: object

In [ ]:
pred_train['final_pred'] = pred_train['ensemble_pred'].apply(lambda x:stats.mode(x)[0][0] if len(set(x))<2 else x[1])

In [ ]:
precision_score(y_train,pred_train['final_pred'],average=None)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
pred_validate = pd.DataFrame(y_validate_pred,columns=['DT_pred'])
pred_validate['RF_pred'] = y_rf_validate
pred_validate['KNN_pred'] = y_knn_validate
pred_validate['ensemble_pred'] = pred_validate.apply(lambda x:list(x),axis=1)
pred_validate['final_pred'] = pred_validate['ensemble_pred'].apply(lambda x:stats.mode(x)[0][0] if len(set(x))<2 else x[1])

In [ ]:
score['ensemble_validate_precision'] = precision_score(y_validate,pred_validate['final_pred'],average=None)
score['ensemble_validate_recall'] = recall_score(y_validate,pred_validate['final_pred'],average=None)


In [ ]:
score

Label_Id  ... ensemble_validate_recall
0         0  ...                 0.995780
1         1  ...                 0.995515
2         2  ...                 0.990474
3         3  ...                 0.994489
4         4  ...                 0.991723
5         5  ...                 0.998488
6         6  ...                 0.992511
7         7  ...                 0.995735
8         8  ...                 0.993773
9         9  ...                 0.992279

[10 rows x 15 columns]

In [ ]:
score[['rf_validate_precision','ensemble_validate_precision','rf_validate_recall','ensemble_validate_recall']]

rf_validate_precision  ...  ensemble_validate_recall
0               0.994792  ...                  0.995780
1               0.995267  ...                  0.995515
2               0.994212  ...                  0.990474
3               0.992252  ...                  0.994489
4               0.995970  ...                  0.991723
5               0.993482  ...                  0.998488
6               0.995493  ...                  0.992511
7               0.992746  ...                  0.995735
8               0.995261  ...                  0.993773
9               0.991291  ...                  0.992279

[10 rows x 4 columns]

In [ ]:
y_knn_test = model_knn.predict(X_test)

In [ ]:
pred_test = pd.DataFrame(y_test_pred,columns=['dt_pred'])
pred_test['rf_pred'] = y_rf_test
pred_test['knn_pred'] = y_knn_test
pred_test['ensemble_pred'] = pred_test.apply(lambda x:list(x),axis=1)
pred_test['final_pred'] = pred_test['ensemble_pred'].apply(lambda x: stats.mode(x)[0][0] if len(set(x))<=2 else x[1])

In [ ]:
test_data['ensemble_pred'] = encode.inverse_transform(pred_test['final_pred'])

In [ ]:
test_data[['row_id','ensemble_pred']].rename(columns={"ensemble_pred":"target"}).to_csv('submission_ensemble.csv',index=False)

In [ ]:
!kaggle competitions submit -c tabular-playground-series-feb-2022 -f submission_ensemble.csv -m 'KNN bagged with RF'

100% 2.71M/2.71M [00:00<00:00, 10.4MB/s]
Successfully submitted to Tabular Playground Series - Feb 2022